name: dovy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  after_layout: ^1.0.7+2
  bloc: ^6.0.0
  chopper: ^3.0.3
  collection: ^1.14.12
  convex_bottom_bar: ^2.4.1
  cupertino_icons: ^0.1.3
  dart_date: ^1.1.0-nullsafety.0
  dart_strapi: ^0.0.3
  dio: ^3.0.9
  equatable: ^1.2.6
  fl_chart: ^0.11.0
  fluro: ^1.7.8
  flushbar: ^1.10.4
  flutter_bloc: ^6.0.0
  # flutter_form_builder: ^4.2.0
  flutter_hooks: ^0.13.1
  flutter_map: ^0.10.1+1
  flutter_spinkit: ^4.1.2+1
  get_it: ^4.0.2
  google_polyline_algorithm: ^2.0.0
  graphql_flutter: ^3.1.0
  hive_flutter: ^0.3.0+2
  hive: ^1.4.1+1
  latlong: ^0.6.1
  lottie: ^0.5.1
  material_design_icons_flutter: ^4.0.5345
  pigment: ^1.0.3
  searchable_dropdown: ^1.1.3
  supercharged: ^1.6.0
  tinycolor: ^1.0.2

dev_dependencies:
  chopper_generator: ^3.0.5
  json_annotation: ^3.0.1
  json_serializable: ^3.4.1
  swagger_dart_code_generator: any
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  collection: ^1.15.0-nullsafety.5
  meta: ^1.3.0-nullsafety.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lottie/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
  class_name: S
  main_locale: es
